[build]
  command = "npm run build"  # El comando para compilar tu proyecto
  publish = "dist"  # La carpeta de salida de la compilación

[[redirects]]
  from = "/*"  # Redirige todas las rutas
  to = "/index.html"  # Redirige a la página principal

[[headers]]
  for = "/*.html"  # Aplica estas configuraciones a todos los archivos HTML
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.css"  # Aplica estas configuraciones a todos los archivos CSS
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"  # Aplica estas configuraciones a todos los archivos JS
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
